Fix comment. Debug

diff --git a/.github/workflows/social-connect.yml b/.github/workflows/social-connect.yml
--- a/.github/workflows/social-connect.yml
+++ b/.github/workflows/social-connect.yml
@@ -157,7 +157,7 @@ jobs:
       - run: yarn run lint
       - name: Dump GitHub context
         # Use to debug github event and check user ids
-        if: false
+        if: true
         env:
           GITHUB_CONTEXT: ${{ toJson(github) }}
         run: |
@@ -176,7 +176,7 @@ jobs:
         if: github.event_name == 'pull_request' && github.event.pull_request.user.login != 'celo-org'
         run: |
           if ${{ steps.fc.outputs.comment-id == 0 }}; then
-            echo "Error: No Changeset Found. You create an empty changeset with `yarn cs add --empty`" && exit 1
+            echo "Error: No Changeset Found. You create an empty changeset with 'yarn cs add --empty'" && exit 1
           else
             echo "Changeset Found"
           fi
